### ISSUE TITLE
Feature / fix to-do list

### ISSUE THREAD

**Issue by jonnybrooks** [jonnybrooks/astroneer_item_graph#1]
## Fixes
- [x] Fix bad dependencies
- [x] Don't sum up permanent resources e.g. printers

## Features
- [x] Order amounts list as chronological "recipe" style list
- [x] Highlight the "selected" item for visibility amongst all the other nodes
- [x] Add Tag System: #2 
- [x] Make it mobile ready
- [x] Add tooltip on node click with additional data. Show on hover over totals list?
- [ ] Filters for edges in the graph, e.g. "I already have this" & whatever arbitrary filters
- [ ] Add "goals", maybe in seperate tabs, which let you priortise multiple items and sum up across them
- [ ] A "reverse dependency" feature which prints out a graph of all things that depend on a given item
- [ ] More expressive API for permalinks and handling stuff like node exclusion
- [ ] Resource symbols in each node
- [ ] Possibly colour nodes by resource type?
- [ ] Do automatic scrap conversions
- [ ] Overhaul UX - make it prettier and more intuitive
- [ ] ~~Separate fabricators from resources?~~
